# Auto-generated by zod-args-parser

_listy_autocomplete() {
  local cur prev commands opts subcommand used_opts filtered_opts

  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  subcommand="${COMP_WORDS[1]}"

  commands="add-items remove-items create-list delete-list view-list help"

  case "$subcommand" in
    add-items|ai)
      opts="--list --items --tags --verbose"
      ;;
    remove-items|ri)
      opts="--list --verbose"
      ;;
    create-list|cl)
      opts="--overwrite --verbose"
      ;;
    delete-list|dl)
      opts="--verbose"
      ;;
    view-list|vl)
      opts="--verbose"
      ;;
    help|h)
      opts="--verbose"
      ;;

  esac

  used_opts=""
  if [[ " ${commands[@]} " =~ " $subcommand " ]]; then
    for word in "${COMP_WORDS[@]:2}"; do
      if [[ "$word" =~ ^- ]]; then
        used_opts+=" $word"
      fi
    done
  fi

  if [[ -n "$opts" ]]; then
    filtered_opts=""
    for opt in $opts; do
      if [[ ! " $used_opts " =~ " $opt " ]]; then
        filtered_opts+="$opt "
      fi
    done
    COMPREPLY=( $(compgen -W "$filtered_opts" -- "$cur") )
    return
  fi

  if [[ "${COMP_CWORD}" -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
  fi
}

complete -F _listy_autocomplete listy
