# Auto-generated by zod-args-parser

# Disable default file completions for listy
complete -c listy -f

# Subcommands
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'add-items' -d 'Add new items to the list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'ai' -d 'Add new items to the list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'remove-items' -d 'Remove items from the list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'ri' -d 'Remove items from the list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'create-list' -d 'Create a new list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'cl' -d 'Create a new list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'delete-list' -d 'Delete a specific list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'dl' -d 'Delete a specific list.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'view-list' -d 'View a specific list or all lists.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'vl' -d 'View a specific list or all lists.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'help' -d 'Show help message for a specific command.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -a 'h' -d 'Show help message for a specific command.'

# Options for 'add-items'
complete -c listy -n '__fish_seen_subcommand_from add-items ai' -l list -f -d 'The name of the list to add items to.'
complete -c listy -n '__fish_seen_subcommand_from add-items ai' -l items -f
complete -c listy -n '__fish_seen_subcommand_from add-items ai' -l tags -f
complete -c listy -n '__fish_seen_subcommand_from add-items ai' -l verbose -f -d 'Enable verbose mode.'

# Options for 'remove-items'
complete -c listy -n '__fish_seen_subcommand_from remove-items ri' -l list -f -d 'The name of the list to remove items from.'
complete -c listy -n '__fish_seen_subcommand_from remove-items ri' -l verbose -f -d 'Enable verbose mode.'

# Options for 'create-list'
complete -c listy -n '__fish_seen_subcommand_from create-list cl' -l overwrite -f -d 'Overwrite the list if it already exists.'
complete -c listy -n '__fish_seen_subcommand_from create-list cl' -l verbose -f -d 'Enable verbose mode.'

# Options for 'delete-list'
complete -c listy -n '__fish_seen_subcommand_from delete-list dl' -l verbose -f -d 'Enable verbose mode.'

# Options for 'view-list'
complete -c listy -n '__fish_seen_subcommand_from view-list vl' -l verbose -f -d 'Enable verbose mode.'

# Options for 'help'
complete -c listy -n '__fish_seen_subcommand_from help h' -l verbose -f -d 'Enable verbose mode.'

# Global options
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -l help -f -d 'Show help message.'
complete -c listy -n 'not __fish_seen_subcommand_from add-items ai remove-items ri create-list cl delete-list dl view-list vl help h' -l version -f -d 'Show listy version.'
