# Auto-generated by zod-args-parser

<#
.DESCRIPTION
**Listy** is a simple CLI to showcase arguments **parsing** and **validation**.

.EXAMPLE
listy --help
listy help add-items
listy add-items --list groceries --items egg,milk,bread --tags food
listy remove-items --list todos clean cook
listy create-list groceries "List of groceries"
listy delete-list groceries
#>
function listy {
    param(
        [Parameter(Position = 0, Mandatory = $false)]
        [string]$subcommand,
        [Parameter(Position = 1, ValueFromRemainingArguments = $true)]
        [string[]]$arguments
    )
    $scriptPath = (Get-Command 'listy.ps1').Source
    if ($scriptPath) {
        $argumentList = @($subcommand) + ($arguments | Where-Object { $_ -notin '--', '--%' }) | Where-Object { $_ -ne '' }
        & $scriptPath @argumentList
        return
    }
    Write-Error "Could not find 'listy.ps1' script"
}

Register-ArgumentCompleter -CommandName 'listy' -ParameterName 'subcommand' -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    $subcommands = @('add-items', 'remove-items', 'create-list', 'delete-list', 'view-list', 'help', '--help', '--version', '--db')
    $subcommands | Where-Object { $_ -like "$wordToComplete*" }
}

Register-ArgumentCompleter -CommandName 'listy' -ParameterName 'arguments' -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    $subcommand = $commandAst.CommandElements[1].Value
    $arguments = switch ($subcommand) {
        'add-items' { @('--list', '--items', '--tags', '--verbose') }
        'ai' { @('--list', '--items', '--tags', '--verbose') }
        'remove-items' { @('--list', '--verbose') }
        'ri' { @('--list', '--verbose') }
        'create-list' { @('--overwrite', '--verbose') }
        'cl' { @('--overwrite', '--verbose') }
        'delete-list' { @('--verbose') }
        'dl' { @('--verbose') }
        'view-list' { @('--verbose') }
        'vl' { @('--verbose') }
        'help' { @('--verbose') }
        'h' { @('--verbose') }
        default { @('--help', '--version', '--db') }
    }
    $arguments | Where-Object { $_ -like "$wordToComplete*" }
}