# Auto-generated by typed-arg-parser

_listy_autocomplete() {
  local ret=1

  _arguments -C \
    '1: :_listy_commands' \
    '*:: :->subcmds' \
    && ret=0

  case $state in
    subcmds)
      case "$words[1]" in
        add-items)
          _arguments \
            '--list[The name of the list to add items to.]' \
            '--items[]' \
            '--tags[]' \
            '--verbose[Enable verbose mode.]' \
            '--debug[Enable debug mode.]' \
            '*: :_files' \
            && ret=0
          ;;
        remove-items)
          _arguments \
            '--list[The name of the list to remove items from.]' \
            '--verbose[Enable verbose mode.]' \
            '--debug[Enable debug mode.]' \
            '*: :_files' \
            && ret=0
          ;;
        create-list)
          _arguments \
            '--overwrite[Overwrite the list if it already exists.]' \
            '--verbose[Enable verbose mode.]' \
            '--debug[Enable debug mode.]' \
            '*: :_files' \
            && ret=0
          ;;
        delete-list)
          _arguments \
            '--verbose[Enable verbose mode.]' \
            '--debug[Enable debug mode.]' \
            '*: :_files' \
            && ret=0
          ;;
        help)
          _arguments \
            '--verbose[Enable verbose mode.]' \
            '--debug[Enable debug mode.]' \
            '*: :_files' \
            && ret=0
          ;;
        *)
          _arguments \
            '*: :_files' \
            && ret=0
          ;;
      esac
      ;;
  esac

  return $ret
}
  
_listy_commands() {
  local -a commands=(
    "add-items:Add new items to the list."
    "remove-items:Remove items from the list."
    "create-list:Create a new list."
    "delete-list:Delete a specific list."
    "help:Print help message for command"
  )

  _describe -t subcommands 'subcommand' commands
}

compdef _listy_autocomplete listy
