import { transformOptionToArgument } from "../parse/parser-utilities.ts";

import type { Cli, Subcommand } from "../types/definitions-types.ts";

/**
 * Generates a Fish shell autocomplete script for a CLI.
 *
 * Instructions:
 *
 * - Save the generated script to Fish's completions directory:
 *
 *   - Run: `mkdir -p ~/.config/fish/completions`
 *   - Save to: `~/.config/fish/completions/<cliName>.fish`
 *   - Fish picks it up automatically — no `source` needed
 */
export function generateFishAutocompleteScript(cliDefinition: Cli): string {
  const subcommands = cliDefinition.subcommands ?? [];
  const cliName = cliDefinition.cliName;

  /** Strip leading '--' or '-' and return a Fish-compatible long/short option flag pair. */
  const buildOptionFlags = (argument: string): string => {
    // transformOptionToArgument produces '--foo' or '-f'
    if (argument.startsWith("--")) {
      return `-l ${argument.slice(2)}`;
    }
    if (argument.startsWith("-")) {
      return `-s ${argument.slice(1)}`;
    }
    return `-l ${argument}`;
  };

  /** Build `complete` lines for a set of options under a given condition. */
  const buildOptionCompletions = (
    options: Array<{ argument: string; description: string }>,
    condition: string,
  ): string => {
    return options
      .map(({ argument, description }) => {
        const flags = buildOptionFlags(argument);
        const descPart = description ? ` -d '${description.replaceAll("'", String.raw`\'`)}'` : "";
        return `complete -c ${cliName} -n '${condition}' ${flags} -f${descPart}`;
      })
      .join("\n");
  };

  /** Resolve options with descriptions for a subcommand. */
  const resolveSubcommandOptions = (subcommand: Subcommand) => {
    if (!subcommand.options) return [];
    return Object.entries(subcommand.options).map(([name, option]) => ({
      argument: transformOptionToArgument(name),
      description: option.meta?.description ?? "",
    }));
  };

  // --- Disable file completions globally for this command ---
  const lines: string[] = [
    "# Auto-generated by zod-args-parser",
    "",
    `# Disable default file completions for ${cliName}`,
    `complete -c ${cliName} -f`,
    "",
  ];

  // --- Subcommand completions (only shown before any subcommand is entered) ---
  const noSubcommandSeen = `not __fish_seen_subcommand_from ${subcommands.map(s => [s.name, ...(s.aliases ?? [])].join(" ")).join(" ")}`;

  if (subcommands.length > 0) {
    lines.push("# Subcommands");

    for (const subcommand of subcommands) {
      const description = subcommand.meta?.description ?? "";
      const descPart = description ? ` -d '${description.replaceAll("'", String.raw`\'`)}'` : "";
      const allNames = [subcommand.name, ...(subcommand.aliases ?? [])];

      for (const name of allNames) {
        lines.push(`complete -c ${cliName} -n '${noSubcommandSeen}' -a '${name}'${descPart}`);
      }
    }

    lines.push("");
  }

  // --- Per-subcommand option completions ---
  for (const subcommand of subcommands) {
    const options = resolveSubcommandOptions(subcommand);
    if (options.length === 0) continue;

    const allNames = [subcommand.name, ...(subcommand.aliases ?? [])];
    const seenCondition = `__fish_seen_subcommand_from ${allNames.join(" ")}`;

    lines.push(`# Options for '${subcommand.name}'`, buildOptionCompletions(options, seenCondition), "");
  }

  // --- Global CLI options (shown only when no subcommand has been entered) ---
  if (cliDefinition.options) {
    const globalOptions = Object.entries(cliDefinition.options).map(([name, option]) => ({
      argument: transformOptionToArgument(name),
      description: option.meta?.description ?? "",
    }));

    if (globalOptions.length > 0) {
      lines.push("# Global options", buildOptionCompletions(globalOptions, noSubcommandSeen), "");
    }
  }

  return lines.join("\n");
}
