import { transformOptionToArgument } from "../parse/parser-helpers.ts";

import type { Cli, Subcommand } from "../types/definitions-types.ts";

/**
 * - Generates a ZSH autocomplete script for your CLI.
 * - The generated script should be added to your `~/.zshrc` or `~/.zsh_profile` file:
 *
 *   - Run: `nano $HOME/.zshrc` or `nano $HOME/.zsh_profile`
 *   - Add the following line: `source <generated script path>`
 *   - Save and reopen zsh to take effect
 */
export function generateZshAutocompleteScript(cliDefinition: Cli): string {
  const subcommands = cliDefinition.subcommands ?? [];

  const genArguments = (command: Subcommand) => {
    const optionsNameDesc = command.options
      ? Object.entries(command.options).map(
          ([name, value]) => `'${transformOptionToArgument(name)}[${value.meta?.description ?? ""}]'`,
        )
      : [];

    return optionsNameDesc.join(" \\\n            ");
  };

  const genSubCommand = (subcommand: Subcommand) => {
    const options = subcommand.options;
    if (!options) return "";
    return String.raw`${subcommand.name})
          _arguments \
            ${genArguments(subcommand)} \
            '*: :_files' \
            && ret=0
          ;;`;
  };

  return String.raw`# Auto-generated by typed-arg-parser

_${cliDefinition.cliName}_autocomplete() {
  local ret=1

  _arguments -C \
    '1: :_${cliDefinition.cliName}_commands' \
    '*:: :->subcmds' \
    && ret=0

  case $state in
    subcmds)
      case "$words[1]" in
        ${subcommands
          .map(subCommand => genSubCommand(subCommand))
          .filter(Boolean)
          .join("\n        ")}
        *)
          _arguments \
            '*: :_files' \
            && ret=0
          ;;
      esac
      ;;
  esac

  return $ret
}
  
_${cliDefinition.cliName}_commands() {
  local -a commands=(
    ${subcommands.map(subcommand => `"${subcommand.name}:${subcommand.meta?.description ?? ""}"`).join("\n    ")}
  )

  _describe -t subcommands 'subcommand' commands
}

compdef _${cliDefinition.cliName}_autocomplete ${cliDefinition.cliName}
`;
}
