import { transformOptionToArgument } from "../parse/parser-utilities.ts";

import type { Cli, Subcommand } from "../types/definitions-types.ts";

/** Generates a Zsh autocomplete script for a CLI, including global options when no subcommand is provided. */
export function generateZshAutocompleteScript(cliDefinition: Cli): string {
  const subcommands = cliDefinition.subcommands ?? [];

  /** Generate the argument strings for a subcommand Format: 'option[description]' */
  const generateArguments = (command: Subcommand) => {
    if (!command.options) return "";
    const arguments_ = Object.entries(command.options).map(([name, option]) => {
      const description = option.meta?.description ?? "";
      return `'${transformOptionToArgument(name)}[${description}]'`;
    });
    return arguments_.join(" \\\n            ");
  };

  /** Generate a case block for a subcommand */
  const generateSubcommandCase = (subcommand: Subcommand) => {
    return String.raw`${subcommand.name})
          _arguments \
            ${generateArguments(subcommand)} \
            '*: :_files' \
            && ret=0
          ;;`;
  };

  const subcommandCases = subcommands
    .map(cmd => generateSubcommandCase(cmd))
    .filter(Boolean)
    .join("\n        ");

  const commandDescriptions = subcommands.map(sub => `"${sub.name}:${sub.meta?.description ?? ""}"`).join("\n    ");

  // Global CLI options (only used when no subcommand is provided)
  const globalOptions = cliDefinition.options
    ? Object.entries(cliDefinition.options)
        .map(([name, option]) => {
          const description = option.meta?.description ?? "";
          return `'${transformOptionToArgument(name)}[${description}]'`;
        })
        .join(" \\\n            ")
    : "";

  const cliName = cliDefinition.cliName;

  return String.raw`# Auto-generated by zod-args-parser

_${cliName}_autocomplete() {
  local ret=1

  _arguments -C \
    '1: :_${cliName}_commands' \
    '*:: :->subcmds' \
    && ret=0

  case $state in
    subcmds)
      case "$words[1]" in
        ${subcommandCases}
        *)
          _arguments \
            ${globalOptions ? globalOptions + " \\\n            " : ""}'*: :_files' \
            && ret=0
          ;;
      esac
      ;;
  esac

  return $ret
}

_${cliName}_commands() {
  local -a commands=(
    ${commandDescriptions}
  )

  _describe -t subcommands 'subcommand' commands
}

compdef _${cliName}_autocomplete ${cliName}
`;
}
